
name: "Run Automated Tests"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "Install dependencies"
        run: |
          npm run install-mm:dev
      - name: "Run tests"
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          touch css/custom.css
          npm run test:prettier
          npm run test:js
          npm run test:css
          npm run test
