
name: "Enforce Pull-Request Rules"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Enforce changelog"
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabels: "Skip Changelog"
      - name: "Enforce develop branch"
        if: ${{ github.base_ref == 'master' && !contains(github.event.pull_request.labels.*.name, 'mastermerge') }}
        run: |
          echo "This PR is based against the master branch and not a release or hotfix."
          echo "Please don't do this. Switch the branch to 'develop'."
          exit 1
        env:
          BASE_BRANCH: ${{ github.base_ref }}
